name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Step 1- Checkout main branch from GitHub
          uses: actions/checkout@v2
        - name: Set up JDK 15
          uses: actions/setup-java@v2
          with:
            java-version: '15.0.1'
        - name: Build with Maven
          run: mvn -B package --file pom.xml
        - name: Step 4- List the current directory
          run: ls -a
        - name: step 5 - What is in target folder
          run: |
            cd target
            ls -a
          
